version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=TODO_CHANGE_ME@liverpool.ac.uk
      - PGADMIN_DEFAULT_PASSWORD=TODO_CHANGE_ME
      # Certificate info
      # TODO: This may differ
      - PGADMIN_ENABLE_TLS=True  # Enable TLS (HTTPS)
      - PGADMIN_TLS_CERTIFICATE=/certs/server.crt  # Path to SSL certificate
      - PGADMIN_TLS_KEY=/certs/server.key  # Path to SSL key
    ports:
      - "443:443"
    volumes:
      # TODO: This may differ
      - ./certs:/certs
      - ./pgadmin_data:/var/lib/pgadmin

  postgres:
    image: postgres
    container_name: postgres
    restart: always  # Automatically restart if the container crashes
    environment:
      - POSTGRES_PASSWORD=TODO_CHANGE_ME
      - POSTGRES_USER=TODO_CHANGE_ME
      - POSTGRES_DB=TODO_CHANGE_ME
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
