version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=TODO_CHANGE_ME@liverpool.ac.uk
      - PGADMIN_DEFAULT_PASSWORD=TODO_CHANGE_ME
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "80:80"

  postgres:
    image: postgres
    container_name: postgres
    restart: always  # Automatically restart if the container crashes
    environment:
      - POSTGRES_PASSWORD=TODO_CHANGE_ME
      - POSTGRES_USER=TODO_CHANGE_ME
      - POSTGRES_DB=TODO_CHANGE_ME
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
